sudo: false
language: node_js
before_install:
  - npm install npm -g
node_js:
  - "0.12"
  - "io.js"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
env:
  - TEST_SUITE=test
script: npm run-script $TEST_SUITE